site_name: DigiDOT Documentation
site_description: Documentation for DigiDOT EHR integrations and interfaces

repo_url: https://github.com/novariiks/digidot-documentation
repo_name: digidot-documentation

theme:
  name: material

  logo: assets/images/novari-logo.svg
  favicon: assets/images/novari-favicon.svg

  palette:
    - scheme: default
      primary: custom
      accent: custom

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences

copyright: >
  © 2026 Novari IKS ·
  <a href="https://novari.no/prosjekter/prosjekt-z/" target="_blank" rel="noopener">
    About the DigiDOT project
  </a>

extra:
  generator: false

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home: index.md

  # - Getting started:
  #     - Overview: getting-started/index.md

  # - Architecture:
  #     - Overview: architecture/index.md
  #     - System context: architecture/system-context.md
  #     - Integration overview: architecture/integration-overview.md

  # - EPJ integration:
  #     - Overview: integration/index.md
  #     - Connectivity: integration/connectivity.md
  #     - Authentication: integration/authentication.md
  #     - Authorization: integration/authorization.md

  # - API:
  #     - Overview: api/index.md
  #     - Conventions: api/conventions.md
  #     - Error handling: api/error-handling.md

  - Profiling and terminology:
      - Overview: data/index.md
      # - Profiling: data/profiling.md
      # - Terminology: data/terminology.md
      # - Implementation guide: data/implementationguide.md

  # - Security:
  #     - Overview: security/index.md
  #     - Requirements: security/requirements.md

  #- References: references/index.md